# -*- coding: utf-8 -*-
"""Program to Find the Maximum Value in a List Using a Loop Without Using max.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zc_x9fDC-JJUrTh2rf5A2rITc7brF8aD
"""

arr = [22, 45, 12, 67, 34]

max_value = arr[0]   # Assume first element is largest

for i in arr:
    if i > max_value:
        max_value = i

print("The maximum value is:", max_value)